name: Test and Score

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pytest
        pip install -r requirements.txt  # Add this if you have a requirements.txt

    - name: Run tests and calculate score
      run: |
        python .github/workflows/calculate_test_score.py
